#Docker MongoDb configuration
spring:
  data:
    mongodb:
      host: 172.18.0.2:27017
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    data-username: md
    password:
    dbcp2:
      driver-class-name: org.h2.Driver
